### ISSUE TITLE
Blaster's auth proxy returns not useful error messages

### ISSUE THREAD

**Issue by wcarlsen** [dfds/blaster#123]
**Describe the bug**
Blaster's auth proxy returns not useful error messages when an error occurs. It was discovered when a user with a DFDS account tried to login but the header cookie could not be parsed in terms of getting an existing email.

**To Reproduce**
1. Fuck up the header cookie. Can be found in auth proxy folder.

**Expected behavior**
Expected useful error messages instead of an exception stack trace.

**Screenshots**
![image](https://user-images.githubusercontent.com/17003032/67977049-8e199780-fc17-11e9-8fe8-60f3254c0ed8.png)

**Comment by ZaradarDFDS** [comment]
I think we will drop the auth proxy once #127 makes it to master :)

**Comment by wcarlsen** [comment]
@SEQUOIIA closing this issue because auth proxy was removed
