### ISSUE TITLE
Security concept

### ISSUE THREAD

**Issue by jcarldk** [dfds/blaster#14]
- [x] Setup a meeting around this
- [x] Whiteboard discussion on how to set it up
- [x] Document this on our wiki the concept

**Comment by jcarldk** [comment]
@dfds/autobots who will update a ADR on the wiki with this

**Comment by jcarldk** [comment]
@ruabr where have you put the documentation?

**Comment by ruabr** [comment]
@jcarldk https://wiki.build.dfds.com/infrastructure/access-flow
