### ISSUE TITLE
Fix broken links to old playbooks

### ISSUE THREAD

**Issue by wcarlsen** [dfds/blaster#201]
Fix broken links to old playbooks site with new wiki js links:
- [x]  src/Blaster.WebApi/Features/Shared/_Layout.cshtml
- [x] src/Blaster.WebApi/Features/Frontpage/Index.cshtml
- [x] src/Blaster.WebApi/Features/Capabilities/Index.cshtml

I couldn't figure out the last one (need help). Check out the already implemented changes in the branch fix-broken-links-to-playbooks (https://github.com/dfds/blaster/commit/485544c43a2dd236195b4302899874d07e743f15).

**Comment by SEQUOIIA** [comment]
https://github.com/dfds/blaster/pull/202
