### ISSUE TITLE
Get our first service into prod in a simpel CI/CD pipeline

### ISSUE THREAD

**Issue by carlsendk** [dfds/blaster#21]
With offset in the _hello world_ edition of our Blaster application, we will create a build and release pipeline in VSTS. We should use the concepts and ideas from our [wiki articles](https://wiki.build.dfds.com/development/kubernetes-pipelines).

__Ingress/routing:__
A suggestion could be. _domain.com_/blaster where _blaster_ is the ingress routing rule that would send traffic to the application.

- [x] create VSTS build definition
- [x] add k8s manifests to hello world application
- [x] define route for ingress (see suggestion above)
- [x] write build script
- [x] add VSTS declarative yaml file and adjust it
- [x] setup release step for PROD (skipping NP for now)

**Comment by jcarldk** [comment]
@jandr-dfds is this closed?
