### ISSUE TITLE
Access to Namespace

### ISSUE THREAD

**Issue by jcarldk** [dfds/blaster#23]
Service account that have access to a namespace (scripted)
Se article in in wiki

**Comment by samdi-dfds** [comment]
Done with this commit
https://dfds.visualstudio.com/DevelopmentExcellence/_git/infrastructure/commit/dce04248fc602182cffa52118da1fa235459c707?refName=refs%2Fheads%2Fmaster

**Comment by jcarldk** [comment]
Closed by @samdi-dfds
