### ISSUE TITLE
Use "Hosted Ubuntu 1604" agent pool

### ISSUE THREAD

**Issue by martinosk** [dfds/blaster#45]
This build is using the *Hosted Linux Preview* pool which is being deprecated on December 1, 2018. We recommend that you move this pipeline to the *Hosted Ubuntu 1604* pool. Instructions for moving your builds can be found here: https://aka.ms/linux-preview-deprecation

**Comment by jakob-nielsen-dfds** [comment]
Thank you Martin. This has now been corrected to use Hosted Ubuntu 1604 and to use the new syntax.
