### ISSUE TITLE
Capability name sync with slack channel does not work when the name start with the same word and "-"

### ISSUE THREAD

**Issue by chaosdudu** [dfds/blaster#47]
**Describe the bug**

**To Reproduce**
1. Go to capabilities page of blaster.
2. Click on add "add a capability in the concept "capability11-capability12"
3.  See slack channel is created for capability11 and slackbot notiications.
4. Click on add "add a capability in the concept "capability11-capability22"
5. No channel is created nor slackbot notifications received.

**Expected behavior**
It is expected to receive the same notifications and slack channel creation for each capability added to the blaster.
![image](https://user-images.githubusercontent.com/43806758/53176260-05f5e380-35ee-11e9-8fd5-cd416f5be74d.png)
![image](https://user-images.githubusercontent.com/43806758/53176289-11e1a580-35ee-11e9-9535-0dc72dd67715.png)

Capabilities takes the first word as input to create the slack channel, once that word is used for the case of same word starting capability name slack channel creation fails. A naming update must be added in order to create slack channels and receive update notifications by each capability.

**Comment by jakob-nielsen-dfds** [comment]
Fixed with commit [51defd01b6d040f28a9414f4c59b08c8a2a21445](https://github.com/dfds/harald/commit/51defd01b6d040f28a9414f4c59b08c8a2a21445).
